[project]
name = "image-processing-and-analysis"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "pooch>=1.8.2",
    "scikit-image>=0.25.2",
]
